name: test linux

on: [push, pull_request, workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      # git checkout the PR
      - uses: actions/checkout@v3
      - name: test DSDL generation
        shell: bash
        run: |
          tests/test_linux.sh

      - name: Archive generated headers
        uses: actions/upload-artifact@v3
        with:
          name: dsdl_generated
          path: |
            tests/dsdl_generated/include/dronecan_msgs.h
            tests/dsdl_generated/include/uavcan.Timestamp.h
            tests/dsdl_generated/src/uavcan.Timestamp.c
          if-no-files-found: error
          retention-days: 7
